// SiteMape.jsx
import React from 'react';

const SiteMape = () => {
  return (
    <div>
<    h4 className=' mt-4 mb-4'><strong>XML Sitemap</strong></h4>

<p>Generated by <span style={{color:"red"}}>YoastSEO</span>, this is an XML Sitemap, meant for consumption by search engines.

You can find more information about XML sitemaps on  <span style={{color:"red"}}>sitemaps.org</span>. <br /> <br />

This XML Sitemap Index file contains 8 sitemaps.</p>
                 </div>)
   
};

export default SiteMape;
