// TermServies.jsx
import React from 'react';

const TermServies = () => {
  return (
    <div>
                
                <hr  style={{height:"4px", color:"black"}}/>
                <h6><strong>Terms of Use</strong></h6>
<h6 className='mb-4 mt-4'><strong>1. BINDING EFFECT</strong></h6>
<p>This is a binding agreement between you and <strong>CourseClub.NET</strong> (us, we, Non-Profit Organization). By using the Internet site located at https://courseclub.me (the Site), you agree to abide by these Terms of Use. If at any time you find these Terms of Use unacceptable, you must immediately leave the Site and cease all use of it</p>
<h6 className=' mt-4 mb-4'><strong>2. PRIVACY POLICY</strong></h6>
<p>We respect your privacy and permit you to control the treatment of your personal information. A complete statement of our current privacy policy can be found by clicking here. Our privacy policy is expressly incorporated into this Agreement by this reference. </p>

<h6 className=' mt-4 mb-4'><strong>3. GOVERNING LAW</strong></h6>

<p>These Terms of Use shall be construed in accordance with and governed by the laws of California and the United States, without reference to rules regarding conflicts of law. This Site is intended for use by individuals based in the United States of America. </p>

<h6 className=' mt-4 mb-4'><strong>4. MINIMUM AGE</strong></h6>

<p>You must be at least 18 years old to access and participate on this site. You guarantee and warrant you are at least 18 years old and are able to enter into this Agreement from a legal perspective. </p>


<h6 className=' mt-4 mb-4'><strong>5. EBOOK SIGNUPS AND MAILINGS</strong></h6>

<p>You have the option, but not obligation, to sign up and receive a free eBook from us. Should you do so, you are agreeing to receive further emailing from us of a commercial nature.</p>

<h6 className=' mt-4 mb-4'><strong>6. EMAIL COMMUNICATIONS</strong></h6>

<p>When you contact us, you expressly consent and agree to receive email responses from us. These email communications may be commercial or non-commercial in nature. Non-commercial emails may include, but are not limited to, administrative issues and announcements of changes to these Terms, the Privacy Policy or other site documentation.

<h6 className=' mt-4 mb-4'><strong>7. USE OF SOFTWARE</strong></h6>



We may make certain software available to you from the Site. If you download software from the Site, the software, including all files and images contained in or generated by the software, and accompanying data (collectively, Software) are deemed to be licensed to you by us, for your personal, noncommercial, home use only. We does not transfer either the title or the intellectual property rights to the Software, and We retains full and complete title to the Software as well as all intellectual property rights therein. You may not sell, redistribute, or reproduce the Software, nor may you decompile, reverse-engineer, disassemble, or otherwise convert the Software to a human-perceivable form. All trademarks and logos are owned by Company or its licencors and you may not copy or use them in any manner.</p>
 </div>
 
  );
};

export default TermServies;
